//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PCShop.rc
//
#define IDR_PCShopTYPE_SRVR_IP          4
#define IDR_PCShopTYPE_SRVR_IP_256      5
#define IDR_PCShopTYPE_SRVR_EMB         6
#define IDR_PCShopTYPE_CNTR_IP          7
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_PCSHOP_FORM                 101
#define IDP_FAILED_TO_CREATE            102
#define IDP_FAILED_OPEN_DATABASE        103
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_PCShopTYPE                  130
#define ID_WINDOW_MANAGER               131
#define IDS_EDIT_MENU                   306
#define IDR_RACKS_VIEW                  307
#define IDR_BRANDS_VIEW                 308
#define IDR_MODELS_VIEW                 309
#define IDR_PRODUCT_TYPES_VIEW          310
#define IDD_SHELVES_DIALOG              310
#define IDR_SHELVES_VIEW                311
#define IDR_PRODUCTS_VIEW               312
#define IDD_RACKS_DIALOG                313
#define IDD_PRODUCT_TYPES_DIALOG        314
#define IDD_PRODUCTS_DIALOG             315
#define IDD_DIALOG_CATEGORIES           317
#define IDR_CATEGORIES_VIEW             318
#define IDD_DIALOG_BRANDS               319
#define IDD_DIALOG_MODELS               321
#define IDC_EDIT_SHELF_NUMBER           1000
#define IDC_EDIT_SHELF_NAME             1001
#define IDC_STATIC_SHELF_NUMBER         1002
#define IDC_STATIC_SHELF_NAME           1003
#define IDC_STATIC_SHELF_CAPACITY       1004
#define IDC_EDIT_SHELF_CAPACITY         1005
#define IDC_STATIC_SHELF_SPACE_TAKEN    1006
#define IDC_EDIT_SHELF_SPACE_TAKEN      1007
#define IDC_STATIC_SHELFS_RACK          1008
#define IDC_COMBO_SHELFS_RACK           1009
#define IDC_STATIC_SHELF_PRODUCTS_COUNT 1010
#define IDC_EDIT_SHELF_PRODUCT_COUNT    1011
#define IDC_EDIT_RACK_ID                1013
#define IDC_EDIT_RACKS_RACK_NAME        1014
#define IDC_STATIC_RACK_ID              1015
#define IDC_STATIC_RACK_NAME            1016
#define IDC_LIST_RACKS_SHELVES          1017
#define IDC_STATIC_RACKS_SHELVES        1018
#define IDC_STATIC_PTS_NAME             1019
#define IDC_STATIC_PTS_SIZE             1020
#define IDC_STATIC_PTS_PRICE            1021
#define IDC_STATIC_PTS_QUANTITY         1022
#define IDC_STATIC_PTS_MODEL            1023
#define IDC_STATIC_PTS_CATEGORY         1024
#define IDC_STATIC_PTS_BRAND            1025
#define IDC_STATIC_PTS_DESCRIPTION      1026
#define IDC_EDIT_PTS_NAME               1027
#define IDC_EDIT_PTS_SIZE               1028
#define IDC_EDIT_PTS_QUANTITY           1029
#define IDC_EDIT_PTS_PRICE              1030
#define IDC_EDIT_PTS_DESCRIPTION        1031
#define IDC_COMBO_PTS_MODEL             1032
#define IDC_COMBO_PTS_CATEGORY          1033
#define IDC_COMBO_PTS_BRAND             1034
#define IDC_EDIT_P_NAME                 1038
#define IDC_EDIT_P_SIZE                 1039
#define IDC_COMBO_P_MODEL               1041
#define IDC_COMBO_P_CATEGORY            1042
#define IDC_COMBO_P_BRAND               1043
#define IDC_EDIT_P_DESCRIPTION          1044
#define IDC_STATIC_P_NAME               1045
#define IDC_STATIC_P_SIZE               1046
#define IDC_STATIC_P_PRICE              1047
#define IDC_STATIC_P_MODEL              1049
#define IDC_STATIC_P_CATEGORY           1050
#define IDC_STATIC_P_BRAND              1051
#define IDC_STATIC_P_DESCRIPTION        1052
#define IDC_STATIC_P_SERIAL_NUM         1053
#define IDC_EDIT_P_SERIAL_NUM           1054
#define IDC_STATIC_P_REGISTER_DATE      1055
#define IDC_EDIT_P_REGISTER_DATE        1056
#define IDC_STATIC_P_SOLD_DATE          1057
#define IDC_EDIT_P_SOLD_DATE            1058
#define IDC_STATIC_P_ADDRESS_DATE       1059
#define IDC_EDIT_P_ADDRESS_DATE         1060
#define IDC_STATIC_P_PT_INFO            1061
#define IDC_STATIC_P_P_INFO             1062
#define IDC_EDIT_P_PRICE                1063
#define IDC_COMBO_P_SHELF               1064
#define IDC_COMBO_P_RACK                1065
#define IDC_STATIC_P_SHELF              1066
#define IDC_STATIC_P_RACK               1067
#define IDC_EDIT_CATEGORIES_CATEGORY_NAME 1068
#define IDC_STATIC_CATEGORIES_CATEGORY_NAME 1069
#define IDC_STATIC_BRANDS_NAME          1070
#define IDC_EDIT_BRANDS_NAME            1071
#define IDC_LIST_BRANDS_MODELS          1072
#define IDC_STATIC_BRANDS_MODELS        1073
#define IDC_EDIT_MODELS_NAME            1074
#define IDC_STATIC_MODELS_NAME          1075
#define IDC_EDIT_MODELS_BRAND           1076
#define IDC_STATIC_MODELS_BRAND         1077
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_CANCEL_EDIT_SRVR             32769
#define INSERT_SHELF_OPTION             32770
#define UPDATE_SHELF_OPTION             32771
#define ID_PRODUCTTYPES                 32772
#define PREVIEW_SHELF_OPTION            32773
#define ID_PRODUCTS                     32774
#define DELETE_SHELF_OPTION             32775
#define ID_SHELVES                      32776
#define INSERT_RACK_OPTION              32777
#define ID_RACKS                        32778
#define UPDATE_RACK_OPTION              32779
#define ID_MODELS                       32780
#define PREVIEW_RACK_OPTION             32781
#define ID_BRANDS                       32782
#define DELETE_RACK_OPTION              32783
#define ID_Menu                         32784
#define INSERT_PRODUCT_TYPE_OPTION      32785
#define INSERT_PRODUCT_OPTION           32786
#define UPDATE_PRODUCT_TYPE_OPTION      32787
#define UPDATE_PRODUCT_OPTION           32788
#define PREVIEW_PRODUCT_TYPE_OPTION     32789
#define PREVIEW_PRODUCT_OPTION          32790
#define DELETE_PRODUCT_TYPE_OPTION      32791
#define DELETE_PRODUCT_OPTION           32792
#define INSERT_CATEGORY_OPTION          32793
#define UPDATE_CATEGORY_OPTION          32794
#define PREVIEW_CATEGORY_OPTION         32795
#define DELETE_CATEGORY_OPTION          32796
#define INSERT_BRAND_OPTION             32797
#define UPDATE_BRAND_OPTION             32798
#define PREVIEW_BRAND_OPTION            32799
#define DELETE_BRAND_OPTION             32800
#define INSERT_MODEL_OPTION             32801
#define UPDATE_MODEL_OPTION             32802
#define PREVIEW_MODEL_OPTION            32803
#define DELETE_MODEL_OPTION             32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        323
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           321
#endif
#endif
