USE [master]
GO

IF EXISTS (SELECT * FROM sys.databases WHERE name = 'PhoneBook')
	DROP DATABASE PhoneBook
GO

CREATE DATABASE [PhoneBook]
 CONTAINMENT = NONE
 ON  PRIMARY 
( 
	NAME = N'Phone_Book',
	FILENAME = N'D:\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PhoneBook.mdf' ,
	SIZE = 8192KB ,
	MAXSIZE = UNLIMITED,
	FILEGROWTH = 65536KB 
)
 LOG ON 
( 
	NAME = N'Phone_Book_log',
	FILENAME = N'D:\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PhoneBook.ldf' , 
	SIZE = 8192KB , 
	MAXSIZE = 2048GB , 
	FILEGROWTH = 65536KB 
)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
