USE [PhoneBook]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PHONE_NUMBERS]') AND type in (N'U'))
	DROP TABLE [dbo].[PHONE_NUMBERS]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PHONE_TYPES]') AND type in (N'U'))
	DROP TABLE [dbo].[PHONE_TYPES]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PERSONS]') AND type in (N'U'))
	DROP TABLE [dbo].[PERSONS]
GO
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CITIES]') AND type in (N'U'))
	DROP TABLE [dbo].[CITIES]
GO


CREATE TABLE CITIES(
	ID int IDENTITY(1,1) NOT NULL,
	UPDATE_COUNTER int NOT NULL,
	CITY_NAME nchar(256) NOT NULL,
	REGION nchar(256) NOT NULL,
)
GO

CREATE TABLE PHONE_TYPES(
	ID int IDENTITY(1,1) NOT NULL,
	UPDATE_COUNTER int NOT NULL,
	PHONE_TYPE nchar(256) NOT NULL
)
GO

CREATE TABLE PERSONS(
	ID int IDENTITY(1,1) NOT NULL,
	UPDATE_COUNTER int NOT NULL,
	FIRST_NAME nchar(128) NOT NULL,
	MIDDLE_NAME nchar(128) NOT NULL,
	LAST_NAME nchar(128) NOT NULL,
	UCN nchar(32) UNIQUE NOT NULL, 
	CITY_ID int NOT NULL,
	ADDRESS nchar(256) NOT NULL,
)
GO

CREATE TABLE PHONE_NUMBERS(
	ID int IDENTITY(1,1) NOT NULL,
	UPDATE_COUNTER int NOT NULL,
	PERSON_ID int NOT NULL,
	PHONE_TYPE_ID int NOT NULL,
	NUMBER nchar(32) NOT NULL
)

--PK, FK
ALTER TABLE PHONE_TYPES
ADD CONSTRAINT PK_PHONE_TYPES_ID PRIMARY KEY (ID) 

ALTER TABLE CITIES
ADD CONSTRAINT PK_CITIES_ID PRIMARY KEY (ID)

ALTER TABLE PERSONS
ADD CONSTRAINT PK_PERSONS_ID PRIMARY KEY (ID),
CONSTRAINT FK_PERSONS_CITY_ID FOREIGN KEY (CITY_ID) REFERENCES CITIES(ID)

ALTER TABLE PHONE_NUMBERS
ADD CONSTRAINT PK_PHONE_NUMBERS_ID PRIMARY KEY (ID),
CONSTRAINT FK_PHONE_NUMBERS_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES PERSONS(ID),
CONSTRAINT FK_PHONE_NUMBERS_PHONE_TYPE_ID FOREIGN KEY (PHONE_TYPE_ID) REFERENCES PHONE_TYPES(ID)

--IX, UX
CREATE INDEX IX_PHONE_NUMBERS_PERSON_ID
    ON dbo.PHONE_NUMBERS(PERSON_ID); 

CREATE UNIQUE INDEX UX_PHONE_NUMBERS_NUMBER
    ON dbo.PHONE_NUMBERS(NUMBER); 

CREATE INDEX IX_PERSONS_CITY_ID
    ON dbo.PERSONS(CITY_ID); 

CREATE INDEX IX_PERSONS_FIRST_NAME
    ON dbo.PERSONS(FIRST_NAME); 

CREATE INDEX IX_PERSONS_LAST_NAME
    ON dbo.PERSONS(LAST_NAME); 

CREATE UNIQUE INDEX IX_PERSONS_UCN
    ON dbo.PERSONS(UCN); 
GO